services:
  db:
    image: mysql:8.0
    container_name: mysql-restaurant
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: db_restaurant
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot" ]
      timeout: 5s
      retries: 10
  app:
    build: .
    container_name: restaurant-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_restaurant?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  mysql_data: